version: "3"

services:
  webserver:
    build:
      context: ./.docker/php
    container_name: themosis-playground-webserver
    restart: 'always'
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT}:80"
      - "${HOST_MACHINE_SECURE_HOST_PORT}:443"
      - "8000:8000"
    links:
      - mysql
    volumes:
      - ${DOCUMENT_ROOT-./}:/var/www/html
      - ${PHP_INI-./.docker/php/php.ini}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR-./.docker/apache}:/etc/apache2/sites-enabled
      - ${LOG_DIR-./.docker/apache/logs}:/var/log/apache2

  mysql:
    image: mysql:5.7
    container_name: themosis-playground-db
    restart: unless-stopped
    tty: true
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./.docker/db/data}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./.docker/db/logs}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}